
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  display:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Display env variables
        run: |
            echo "Var 1 es ${{ secrets.REACT_APP_API_KEY }}"
            echo "Var 1 es ${{ secrets.REACT_APP_AUTH_DOMAIN }}".

